from functions.emoji import emoji

CANAIS_OPCOES = [
    ("canal_de_evento_de_compras", "Evento de Compras", emoji.textc),
    ("canal_de_boas_vindas", "Boas-vindas", emoji.textc),
    ("canal_de_logs_do_sistema", "Logs do Sistema", emoji.textc),
    ("canal_de_logs_de_entradas", "Logs de Entradas", emoji.textc),
    ("canal_de_logs_de_saidas", "Logs de Saídas", emoji.textc),
    ("canal_de_logs_de_mensagens", "Logs de Mensagens", emoji.textc),
    ("canal_de_logs_de_trafego_em_call", "Logs de Tráfego em Call", emoji.textc),
    ("canal_de_logs_de_pedidos", "Logs de Pedidos", emoji.textc),
    ("canal_de_feedback", "Feedback", emoji.textc),
    ("canal_de_logs_de_tickets", "Logs de Tickets", emoji.textc),
    ("canal_de_logs_de_comandos", "Logs de Comandos", emoji.textc),
    ("canal_de_logs_de_anti_falso", "Logs de Anti-Fake", emoji.textc),
    ("canal_de_logs_de_banimentos", "Logs de Banimentos", emoji.textc),
    ("canal_de_logs_de_expulsoes", "Logs de Expulsões", emoji.textc),
    ("canal_de_logs_de_castigos", "Logs de Castigos", emoji.textc),
    ("canal_de_logs_de_cargos_adicionados", "Cargos Adicionados", emoji.route),
    ("canal_de_logs_de_cargos_removidos", "Cargos Removidos", emoji.route),
    ("canal_de_logs_de_cargos_criados", "Cargos Criados", emoji.route),
    ("canal_de_logs_de_cargos_excluidos", "Cargos Excluídos", emoji.route),
    ("canal_de_logs_de_cargos_editados", "Cargos Editados", emoji.route),
    ("canal_de_logs_de_canais_criados", "Canais Criados", emoji.route),
    ("canal_de_logs_de_canais_excluidos", "Canais Excluídos", emoji.route),
    ("canal_de_logs_de_canais_editados", "Canais Editados", emoji.route),
    ("canal_de_logs_de_permissoes_adicionadas", "Permissões Adicionadas", emoji.route),
    ("canal_de_logs_de_permissoes_removidas", "Permissões Removidas", emoji.route),
]